services:
  restapi-mongodb:
    container_name: restapi-mongodb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-mongodb
    environment:
      - MONGODB_URI=mongodb://db-mongodb:27017/test
      - PORT=5000
    ports:
      - 5000:5000
    networks:
      restapi-mongodb-network:
        ipv4_address: 192.168.100.5


  db-mongodb:
    container_name: db-mongodb
    image: mongo:noble
    ports:
      - 27017:27017
    networks:
      restapi-mongodb-network:
        ipv4_address: 192.168.100.10
    volumes:
      - persistent-db:/data/db
    cpus: "0.5"
    mem_limit: 2gb


networks:
  restapi-mongodb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

volumes:
 persistent-db: